import type { Metadata } from "next";
import { cookies } from "next/headers";
// import { Geist } from "next/font/google";
import { Toaster } from "react-hot-toast";
import SiteFooter from "@/components/SiteFooter";
import { DEFAULT_THEME, THEME_COOKIE_NAME } from "@/lib/theme";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";
export const revalidate = 0;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialTheme = cookieStore.get(THEME_COOKIE_NAME)?.value === "dark" ? "dark" : DEFAULT_THEME;

  return (
    <html
      lang="en"
      data-theme={initialTheme}
      className={`${initialTheme === "dark" ? "theme-dark" : "theme-light"}`}
      style={{ colorScheme: initialTheme }}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        {children}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 20000, // 20 seconds
            style: {
              background: '#363636',
              color: '#fff',
            },
          }}
        />
        <SiteFooter />
      </body>
    </html>
  );
}
